### ISSUE TITLE
CreateRelease fails with Auth fail

### ISSUE THREAD

**Issue by topalavlad** [ru-fix/gradle-release-plugin#6]
When running `createRelease` I get the following log:

```
17:34:46.389 [LIFECYCLE] [ru.fix.gradle.release.plugin.GitRepository] Using not-default jsch
17:34:46.389 [LIFECYCLE] [ru.fix.gradle.release.plugin.GitRepository] Found known hosts at: /Users/vladtopala/.ssh/known_hosts
17:34:46.391 [LIFECYCLE] [ru.fix.gradle.release.plugin.GitRepository] Configure session for host: bitbucket.org
17:34:47.273 [LIFECYCLE] [ru.fix.gradle.release.plugin.GitRepository] Configure session for host: bitbucket.org
17:34:48.076 [LIFECYCLE] [ru.fix.gradle.release.plugin.GitRepository] Configure session for host: bitbucket.org
17:34:48.869 [ERROR] [org.gradle.api.Project] Failed to fetch tags from remote repository.
```

and the bottom exception:
```
 Caused by: com.jcraft.jsch.JSchException: Auth fail
17:34:48.883 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.jcraft.jsch.Session.connect(Session.java:519)
17:34:48.883 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:145)
17:34:48.883 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 87 more
```

all git commands work from the terminal so I couldn't figure out anything wrong. I also cleared my `known_hosts` file and only left one key in `.ssh` but that didn't help either.

Any ideas on what I else I could check? My target is BitBucket and I already have my key saved and is usable manually from the terminal.

**Comment by topalavlad** [comment]
I solved this by generating a new key with `ssh-keygen -t rsa -m PEM` based on this [stackoverflow](https://stackoverflow.com/a/53783283) thread and by adding a specific ssh configuration for bitbucket.

```
Host bitbucket.org
        User git
        IdentityFile ~/.ssh/bitbucket_rsa
        PreferredAuthentications publickey
```

**Comment by swarmshine** [comment]
Hello, @topalavlad 
Thank you! Your feedback was very helpful! 
I updated readme and added "well know problems" with your case in it.
https://github.com/ru-fix/gradle-release-plugin#well-known-issues
